// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)

// Signature is the predicate function for signature builders.
type Signature func(*sql.Selector)
