// Code generated by ent, DO NOT EDIT.

package database

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jurshsmith/vaultstream/database/predicate"
	"github.com/jurshsmith/vaultstream/database/signature"
)

// SignatureUpdate is the builder for updating Signature entities.
type SignatureUpdate struct {
	config
	hooks    []Hook
	mutation *SignatureMutation
}

// Where appends a list predicates to the SignatureUpdate builder.
func (su *SignatureUpdate) Where(ps ...predicate.Signature) *SignatureUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetKeyID sets the "key_id" field.
func (su *SignatureUpdate) SetKeyID(i int) *SignatureUpdate {
	su.mutation.ResetKeyID()
	su.mutation.SetKeyID(i)
	return su
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (su *SignatureUpdate) SetNillableKeyID(i *int) *SignatureUpdate {
	if i != nil {
		su.SetKeyID(*i)
	}
	return su
}

// AddKeyID adds i to the "key_id" field.
func (su *SignatureUpdate) AddKeyID(i int) *SignatureUpdate {
	su.mutation.AddKeyID(i)
	return su
}

// SetValue sets the "value" field.
func (su *SignatureUpdate) SetValue(s string) *SignatureUpdate {
	su.mutation.SetValue(s)
	return su
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (su *SignatureUpdate) SetNillableValue(s *string) *SignatureUpdate {
	if s != nil {
		su.SetValue(*s)
	}
	return su
}

// Mutation returns the SignatureMutation object of the builder.
func (su *SignatureUpdate) Mutation() *SignatureMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SignatureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SignatureUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SignatureUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SignatureUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SignatureUpdate) check() error {
	if v, ok := su.mutation.KeyID(); ok {
		if err := signature.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`database: validator failed for field "Signature.key_id": %w`, err)}
		}
	}
	if v, ok := su.mutation.Value(); ok {
		if err := signature.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`database: validator failed for field "Signature.value": %w`, err)}
		}
	}
	if su.mutation.RecordCleared() && len(su.mutation.RecordIDs()) > 0 {
		return errors.New(`database: clearing a required unique edge "Signature.record"`)
	}
	return nil
}

func (su *SignatureUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(signature.Table, signature.Columns, sqlgraph.NewFieldSpec(signature.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.KeyID(); ok {
		_spec.SetField(signature.FieldKeyID, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedKeyID(); ok {
		_spec.AddField(signature.FieldKeyID, field.TypeInt, value)
	}
	if value, ok := su.mutation.Value(); ok {
		_spec.SetField(signature.FieldValue, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SignatureUpdateOne is the builder for updating a single Signature entity.
type SignatureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignatureMutation
}

// SetKeyID sets the "key_id" field.
func (suo *SignatureUpdateOne) SetKeyID(i int) *SignatureUpdateOne {
	suo.mutation.ResetKeyID()
	suo.mutation.SetKeyID(i)
	return suo
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (suo *SignatureUpdateOne) SetNillableKeyID(i *int) *SignatureUpdateOne {
	if i != nil {
		suo.SetKeyID(*i)
	}
	return suo
}

// AddKeyID adds i to the "key_id" field.
func (suo *SignatureUpdateOne) AddKeyID(i int) *SignatureUpdateOne {
	suo.mutation.AddKeyID(i)
	return suo
}

// SetValue sets the "value" field.
func (suo *SignatureUpdateOne) SetValue(s string) *SignatureUpdateOne {
	suo.mutation.SetValue(s)
	return suo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (suo *SignatureUpdateOne) SetNillableValue(s *string) *SignatureUpdateOne {
	if s != nil {
		suo.SetValue(*s)
	}
	return suo
}

// Mutation returns the SignatureMutation object of the builder.
func (suo *SignatureUpdateOne) Mutation() *SignatureMutation {
	return suo.mutation
}

// Where appends a list predicates to the SignatureUpdate builder.
func (suo *SignatureUpdateOne) Where(ps ...predicate.Signature) *SignatureUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SignatureUpdateOne) Select(field string, fields ...string) *SignatureUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Signature entity.
func (suo *SignatureUpdateOne) Save(ctx context.Context) (*Signature, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SignatureUpdateOne) SaveX(ctx context.Context) *Signature {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SignatureUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SignatureUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SignatureUpdateOne) check() error {
	if v, ok := suo.mutation.KeyID(); ok {
		if err := signature.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`database: validator failed for field "Signature.key_id": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Value(); ok {
		if err := signature.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`database: validator failed for field "Signature.value": %w`, err)}
		}
	}
	if suo.mutation.RecordCleared() && len(suo.mutation.RecordIDs()) > 0 {
		return errors.New(`database: clearing a required unique edge "Signature.record"`)
	}
	return nil
}

func (suo *SignatureUpdateOne) sqlSave(ctx context.Context) (_node *Signature, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signature.Table, signature.Columns, sqlgraph.NewFieldSpec(signature.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`database: missing "Signature.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signature.FieldID)
		for _, f := range fields {
			if !signature.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("database: invalid field %q for query", f)}
			}
			if f != signature.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.KeyID(); ok {
		_spec.SetField(signature.FieldKeyID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedKeyID(); ok {
		_spec.AddField(signature.FieldKeyID, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Value(); ok {
		_spec.SetField(signature.FieldValue, field.TypeString, value)
	}
	_node = &Signature{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
