// Code generated by ent, DO NOT EDIT.

package database

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jurshsmith/vaultstream/database/record"
	"github.com/jurshsmith/vaultstream/database/signature"
)

// SignatureCreate is the builder for creating a Signature entity.
type SignatureCreate struct {
	config
	mutation *SignatureMutation
	hooks    []Hook
}

// SetRecordID sets the "record_id" field.
func (sc *SignatureCreate) SetRecordID(i int) *SignatureCreate {
	sc.mutation.SetRecordID(i)
	return sc
}

// SetKeyID sets the "key_id" field.
func (sc *SignatureCreate) SetKeyID(i int) *SignatureCreate {
	sc.mutation.SetKeyID(i)
	return sc
}

// SetValue sets the "value" field.
func (sc *SignatureCreate) SetValue(s string) *SignatureCreate {
	sc.mutation.SetValue(s)
	return sc
}

// SetInsertedAt sets the "inserted_at" field.
func (sc *SignatureCreate) SetInsertedAt(t time.Time) *SignatureCreate {
	sc.mutation.SetInsertedAt(t)
	return sc
}

// SetNillableInsertedAt sets the "inserted_at" field if the given value is not nil.
func (sc *SignatureCreate) SetNillableInsertedAt(t *time.Time) *SignatureCreate {
	if t != nil {
		sc.SetInsertedAt(*t)
	}
	return sc
}

// SetRecord sets the "record" edge to the Record entity.
func (sc *SignatureCreate) SetRecord(r *Record) *SignatureCreate {
	return sc.SetRecordID(r.ID)
}

// Mutation returns the SignatureMutation object of the builder.
func (sc *SignatureCreate) Mutation() *SignatureMutation {
	return sc.mutation
}

// Save creates the Signature in the database.
func (sc *SignatureCreate) Save(ctx context.Context) (*Signature, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SignatureCreate) SaveX(ctx context.Context) *Signature {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SignatureCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SignatureCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SignatureCreate) defaults() {
	if _, ok := sc.mutation.InsertedAt(); !ok {
		v := signature.DefaultInsertedAt()
		sc.mutation.SetInsertedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SignatureCreate) check() error {
	if _, ok := sc.mutation.RecordID(); !ok {
		return &ValidationError{Name: "record_id", err: errors.New(`database: missing required field "Signature.record_id"`)}
	}
	if _, ok := sc.mutation.KeyID(); !ok {
		return &ValidationError{Name: "key_id", err: errors.New(`database: missing required field "Signature.key_id"`)}
	}
	if v, ok := sc.mutation.KeyID(); ok {
		if err := signature.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`database: validator failed for field "Signature.key_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`database: missing required field "Signature.value"`)}
	}
	if v, ok := sc.mutation.Value(); ok {
		if err := signature.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`database: validator failed for field "Signature.value": %w`, err)}
		}
	}
	if _, ok := sc.mutation.InsertedAt(); !ok {
		return &ValidationError{Name: "inserted_at", err: errors.New(`database: missing required field "Signature.inserted_at"`)}
	}
	if len(sc.mutation.RecordIDs()) == 0 {
		return &ValidationError{Name: "record", err: errors.New(`database: missing required edge "Signature.record"`)}
	}
	return nil
}

func (sc *SignatureCreate) sqlSave(ctx context.Context) (*Signature, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SignatureCreate) createSpec() (*Signature, *sqlgraph.CreateSpec) {
	var (
		_node = &Signature{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(signature.Table, sqlgraph.NewFieldSpec(signature.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.KeyID(); ok {
		_spec.SetField(signature.FieldKeyID, field.TypeInt, value)
		_node.KeyID = value
	}
	if value, ok := sc.mutation.Value(); ok {
		_spec.SetField(signature.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := sc.mutation.InsertedAt(); ok {
		_spec.SetField(signature.FieldInsertedAt, field.TypeTime, value)
		_node.InsertedAt = value
	}
	if nodes := sc.mutation.RecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   signature.RecordTable,
			Columns: []string{signature.RecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecordID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SignatureCreateBulk is the builder for creating many Signature entities in bulk.
type SignatureCreateBulk struct {
	config
	err      error
	builders []*SignatureCreate
}

// Save creates the Signature entities in the database.
func (scb *SignatureCreateBulk) Save(ctx context.Context) ([]*Signature, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Signature, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignatureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SignatureCreateBulk) SaveX(ctx context.Context) []*Signature {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SignatureCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SignatureCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
